[package]
name = "redis-rust-test"
version = "0.1.0"
authors = ["Esteve Llado <ellado@fundaciobit.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.16.0"
